# Site settings
title: 没想好标题
email: veizzsmile#gmail.com
description: > # this means to ignore newlines until "baseurl:"
    沉思录，学习笔记
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://veizz.github.io" # the base hostname & protocol for your site
twitter_username: veizz
github_username:  veizz

# Build settings
markdown: kramdown
